### ISSUE TITLE
AppVeyor badge url

### ISSUE THREAD

**Issue by martinRenou** [pybind/pybind11_json#10]
@wjakob last time I ping you, I promise!

The appveyor badge url is wrong on the README, but I don't seem to have the authorization for getting access to the `pybind/pybind11_json` project on AppVeyor (because I'm not part of the organization).  So I am not able to find this badge url. 

Would you mind sharing the url here or fixing the README?

**Comment by wjakob** [comment]
No worries, here it is: https://ci.appveyor.com/api/projects/status/d31t6dytkfm28tfo?svg=true

Best,
Wenzel

**Comment by martinRenou** [comment]
Thanks!
