### ISSUE TITLE
C++ returning nlohmann::json to Python. Is it possible?

### ISSUE THREAD

**Issue by nyckmaia** [pybind/pybind11_json#18]
I'm building a C++ Pybind11 module to use my C++ functions inside some Python scripts.
 
I would like to know if is possible to write a C++ function that returns a `nlohmann::json` type and get this output result in the Python side as JSON...or dict...?? 

**Example: C++ side**
```
nlohmann::json my_func()
{
    nlohmann::json j;

    j["key_a"] = 0;
    j["key_b"] = 1;
    j["tree"]["first"] = "node 1";

    return j;
}
```
**Python side:**
```
import my_module

data = my_module.my_func()
```
**How can I do that?**

**Comment by JohanMabille** [comment]
I think that if `my_func` returns a py::object, it should work:

```cpp
py::object my_func()
{
    nlohmann::json j;

    j["key_a"] = 0;
    j["key_b"] = 1;
    j["tree"]["first"] = "node 1";

    return j;
}
```

Returning a `py::object`` forces the conversion in the return statement (and is handled by this package). On the python side you should be able to dump the object as a json:

```python
import json
import my_module

data = my_module.my_func()
data_json = json.dumps(data)
```

**Comment by nyckmaia** [comment]
Thank you @JohanMabille! **All working now!**

**The C++ side:**
```
py::object my_func()
{
    nlohmann::json j;

    j["key_a"] = 0;
    j["key_b"] = 1;
    j["tree"]["first"] = "node 1";

    return j;
}
```

**The Python side:**
```
import my_module

// Just this line works good:
data = my_module.my_func()
```
