### ISSUE TITLE
Error: nlohmann::json as input argument

### ISSUE THREAD

**Issue by nyckmaia** [pybind/pybind11_json#19]
As you can see in this topic #18, I can return a `nlohmann::json` from a Python function as a `pybind11::object` type.

Now, I'm trying to send a JSON as a input argument to `my_func()`, modify it and return it back in my Python script.

**Example: C++ side**
```
pybind11::object my_func(nlohmann::json& a)
{
    a["new"] = "new string";

    return a;
}
```
It compiles Ok, but when I tried to call this function inside my Python module, I got this error below:

**Error: Python side**
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: test(): incompatible function arguments. The following argument types are supported:
    1. (self: my_lib.MusicXML, arg0: nlohmann::basic_json<std::map, std::vector, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, bool, long, unsigned long, double, std::allocator, nlohmann::adl_serializer>) -> object
```
**What I have to do to fix it?**

Thank you,

**Comment by martinRenou** [comment]
You should take a `py::object obj` as argument and do the conversion like this:

```
nl::json j = obj;
```

**Comment by martinRenou** [comment]
This will change in the next release. You will be able to take an `nlohmann::json` as input. The `py::object` to  `nlohmann::json` conversion will be done automatically
