### ISSUE TITLE
How can I debug?

### ISSUE THREAD

**Issue by nyckmaia** [pybind/pybind11_json#21]
I wrote a Pybind11 module and just one function is not working **only when it is called in the Python environment** (C++ side works great).

When I call it in the C++ environment, this function takes 30 seconds to return the result and works great.

This function uses 2 external libraries:

- nlohmann JSON
- pugi XML parser

When I call it in the Python side, I got a error inside the `pugi` library.

```
python3: /src/pugixml.cpp:12202: const pugi::xpath_node& pugi::xpath_node_set::operator[](size_t) const: Assertion `index < size()' failed.

Aborted (core dumped)
```
**How can I debug (line by line) my C++ code in the Python environment?**

**Comment by JohanMabille** [comment]
If you have an IDE, just google to find how to do it. For intance on Windows MSVC has the PTVSD plugin that allows you to start a python process and break into C++ code.

If you don't use an IDE, `std::cout` is your best friend. It seems that you have a core dump, so you should be able to read it with gdb and investigate the root cause of the issue.

**Comment by nyckmaia** [comment]
UPDATE 1
--------------
I found where the error appears, but I don't have any solution yet.
Apparently, the C++ `pugixml` library is behaving differently on C++ and Python environment.

Here is the part of my C++ code where I found the different `std::cout` output:

```
// Select XML nodes in the path 'myPath' using pugixml library
const pugi::xpath_node_set x = _doc.select_nodes(myPath);

// Get the number of XML nodes in 'myPath'
size_t xSize = x.size();

// Print
std::cout << "xSize: " << xSize << std::endl;
```
**Running in the C++ side:**
```
xSize: 2000
```
**Running in the Python side:**
```
xSize: 0
```
**Do you have any ideas?**

**Comment by nyckmaia** [comment]
Sorry, I was passing the wrong argument in the Python function....
Please, forget it...
