### ISSUE TITLE
Move to pybind organization?

### ISSUE THREAD

**Issue by wjakob** [pybind/pybind11_json#4]
Hi Martin,

several projects that integrate pybind11 with other dependencies (abseil, basel, protobuf) are slated to move into the pybind organization (https://github.com/pybind/). I thought that this would also make sense for this project, which is both useful and popular. It's completely up to you, of course. If you would like to move, please let me know and I'll invite you to the organization.

Best,
Wenzel

**Comment by martinRenou** [comment]
Hi Wenzel,

It would make sense indeed. I totally agree with this!

**Comment by wjakob** [comment]
Fantastic -- having briefly looked into this, it seems to me that this is something you would have to initiate (https://help.github.com/en/articles/transferring-a-repository).

**Comment by martinRenou** [comment]
> To transfer a repository that you own to an organization, you must have permission to create a repository in the target organization.

Apparently I need to have permission for creating repositories under the pybind11 organization if I initiate the transfer. Maybe you could remove this permission once I transferred it?

**Comment by martinRenou** [comment]
Or I could give you all the rights on this repo so you can initiate the transfer

**Comment by wjakob** [comment]
Let's do that, it's probably easiest.

**Comment by wjakob** [comment]
Hm, the button to move the repo didn't appear. Let's try the other way -- I added you as a member of the 'pybind' organization.

**Comment by martinRenou** [comment]
Done! :) You can now limit my rights to the `pybind_json` repository if you want.

Also, should we rename the repository `pybind11_json` for homogeneity with other packages in the organization?

**Comment by wjakob** [comment]
I renamed it just now --thanks.

**Comment by wjakob** [comment]
I re-added you as admin on your project.

**Comment by martinRenou** [comment]
Thanks :)
