### ISSUE TITLE
> I've also spotted it when upgrading to 2.3.0.

### ISSUE THREAD

**Issue by damian-cell** [pybind/pybind11_json#47]
> I've also spotted it when upgrading to 2.3.0.
> But the only problem I came across was using such enums as a default arg.
> For example:
> 
> ```c++
> #include <pybind11/pybind11.h>
> namespace py = pybind11;
> 
> enum class X : char { X1, X2 };
> bool foo(X x) { return x == X::X1; }
> 
> PYBIND11_MODULE(example, m) {
>     py::enum_<X>(m, "X").value("X1", X::X1).value("X2", X::X2);
>     m.def("foo", &foo, py::arg("x")=X::X1);
> }
> ```
> 
> In my case the simplest workaround is to change `char` to `signed char` (or `unsigned char`).
> 
> _Originally posted by @wojdyr in [#1820 (comment)](https://github.com/pybind/pybind11/issues/1820#issuecomment-520504069)_

_Originally posted by @damian-cell in https://github.com/pybind/pybind11/issues/2990#issuecomment-841777696_

**Comment by martinRenou** [comment]
Could you provide more information on the issue? I fail to understand how pybind11_json is related.

**Comment by JohanMabille** [comment]
This is specific to pybind11, not related to pybind11_json.
