### ISSUE TITLE
Reactivate TravisCI

### ISSUE THREAD

**Issue by martinRenou** [pybind/pybind11_json#6]
@wjakob would you mind activating TravisCI for this project?

**Comment by wjakob** [comment]
Hi Martin,

is it possible that Travis CI learned about the move, and that it "just works"?
See here for details, it seems to be active: https://travis-ci.org/pybind/pybind11_json

Best,
Wenzel

**Comment by martinRenou** [comment]
Ok good! Sorry for pinging you then. We just need to update the badge on the README.

**Comment by wjakob** [comment]
No worries :)

**Comment by martinRenou** [comment]
Fixed by #7
